### ISSUE TITLE
Error sending transaction

### ISSUE THREAD

**Issue by jordimarch** [sahharYoucef/alephium_wallet#3]
Greetings!

I'm having an error sending transaction. Guess I don't have to write down any quantity for gas or gas price:

l/flutter ( 4274): │ #0   LoggerService.log (package:alephium_wallet/log/logger_service.dart:22:17)
I/flutter ( 4274): │ #1   new ApiError (package:alephium_wallet/api/utils/error_handler.dart:13:30)
I/flutter ( 4274): 
I/flutter ( 4274): │ ⛔   "detail": "Invalid value for: body (missing keys in dictionary: alphAmount at index 201: decoding failure)"
I/flutter ( 4274): │ ⛔ }
I/flutter ( 4274): └───────────────

![a236cb3d-43f9-41f0-b3c3-69fbace34e54](https://user-images.githubusercontent.com/5549010/201692117-4f84da08-f93a-4eda-b28a-cfee2ce7962c.jpg)

Currently @ master e178847b. Saw that alephium_dart was updated with alphAmount vs attoAlphAmount, but to no avail....

Ideas?
Thanks! :)

**Comment by jordimarch** [comment]
I'm using it from latest git + flutter upgrade.

Flutter upgrade said it updated alephium_dart to b504e7, which seems to be latest, too.

**Comment by sahharYoucef** [comment]
Sometimes it doesn't update
Try to remove pubspec.lock then run
Flutter clean
Flutter pub get

**Comment by jordimarch** [comment]
Nope. Tried with what you said above and latest release 0.1.3...

Maybe it's something related to the language itself, because I'm in spanish by default...

**Comment by sahharYoucef** [comment]
i reverted alephium commit ref to the previous one , sending transactions should work in mainnet but not in testnet

**Comment by jordimarch** [comment]
OK! Yes, works perfectly.

Gives an exception trying to save transaction @ sqlite, but otherwise, transaction ended properly:

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/SQLiteLog(18683): (1) table transactions has no column named txID in "INSERT OR REPLACE INTO transactions (txID, txHash, blockHash, transactionGas, wallet_id, tx_address, status, transactionAmount, id, timeStamp, network) VALUES (?
E/flutter (18683): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(table transactions has no column named txID (code 1 SQLITE_ERROR): , while compiling: INSERT OR REPLACE INTO transactions (txID, txHash, blockHash, transactionGas, wallet_id, tx_address, status, transactionAmount, id, timeStamp, network) VALUES (?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?)) sql 'INSERT OR REPLACE INTO transactions (txID, txHash, blockHash, transactionGas, wallet_id, tx_address, status, transactionAmount, id, timeStamp, network) VALUES (?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?)' args [kkkk..., kkkk..., 245480, kkk, kkk, pending, 100000000000, kkk..., 1668500577081, mainnet]

Thanks Sahhar!
